# Generated by Django 4.1.7 on 2023-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=511, verbose_name='description/name')),
                ('img', models.ImageField(upload_to='media/webinars')),
                ('ref', models.CharField(max_length=255, verbose_name='main page ref')),
                ('type', models.CharField(max_length=255, verbose_name='Вебинар, Совещание...')),
            ],
        ),
    ]
