# Generated by Django 4.1.7 on 2023-10-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.IntegerField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='unique id accessor')),
                ('name', models.CharField(max_length=128, verbose_name='description/name')),
                ('Class', models.CharField(max_length=63, verbose_name='common feature')),
                ('rarityCounter', models.IntegerField(verbose_name='Rarity counter')),
                ('Img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=511, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=511, verbose_name='Заголовок вложенного поста')),
                ('img', models.ImageField(null=True, upload_to='media/')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authApp.post', verbose_name='ParentPost')),
            ],
        ),
        migrations.CreateModel(
            name='UsersEmails',
            fields=[
                ('id', models.IntegerField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='unique id mail')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Ref2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ref name')),
                ('ref', models.CharField(max_length=511)),
                ('post2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='authApp.post2', verbose_name='Post2')),
            ],
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ref name')),
                ('ref', models.CharField(max_length=511)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='authApp.post', verbose_name='Post')),
            ],
        ),
        migrations.CreateModel(
            name='File2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('file', models.FileField(upload_to='media/mediacia/')),
                ('post2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authApp.post2', verbose_name='Post2')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('file', models.FileField(upload_to='media/mediacia/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authApp.post', verbose_name='Post')),
            ],
        ),
    ]
