# Generated by Django 4.1.7 on 2023-10-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
    ]
